# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myunsplash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='locale',
            field=models.CharField(max_length=30),
        ),
    ]
