# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myunsplash', '0002_auto_20180928_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='Category',
            new_name='category',
        ),
    ]
