# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-29 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myunsplash', '0004_auto_20180928_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='By',
            field=models.CharField(default=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='image',
            name='Description',
            field=models.CharField(max_length=40000),
        ),
        migrations.AlterField(
            model_name='image',
            name='Name',
            field=models.CharField(max_length=200),
        ),
    ]
