# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-29 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myunsplash', '0005_auto_20180929_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='image',
            name='By',
            field=models.CharField(default=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='image',
            name='Description',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='location',
            name='locale',
            field=models.CharField(max_length=300),
        ),
    ]
